# Official Julia image from https://hub.docker.com/_/julia/
image: julia

.test_template: &test_base
  stage: test
  script:

    # Install required libraries:
    - time apt-get update
    - time apt-get install -qq build-essential $SYSTEM_PACKAGES
    - which $PIP
    - $PIP install --upgrade tox
    - tox --version
    - time tox --recreate --notest

    # Prepare & test:
    - which julia
    - time julia --color=yes ci/prepare.jl
    - make test-full

test-py3:
  <<: *test_base
  variables:
    PIP: pip3
    SYSTEM_PACKAGES: python3-pip

test-py2:
  <<: *test_base
  variables:
    PIP: pip2
    SYSTEM_PACKAGES: python-pip

# Since caching outside repository is impossible
# (https://gitlab.com/gitlab-org/gitlab-ce/issues/4431), I'm using
# $PWD/.julia instead of ~/.julia.  It can be done by JULIA_PKGDIR.
#
# Julia document on JULIA_PKGDIR:
# https://docs.julialang.org/en/stable/manual/environment-variables/#JULIA_PKGDIR-1
variables:
  JULIA_PKGDIR: "$CI_PROJECT_DIR/.julia"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  TOXENV: py

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .julia
    - .pip
