language: python
os:
  - linux
python:
    - "2.7"
    - "3.6"
env:
  TOXENV=py
matrix:
  allow_failures:
    - os:  osx
  include:
    - os: osx
      language: generic
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py BREW_PYTHON=python
notifications:
  email: false
before_install:
  - ci/travis-before_install

  - export PATH="$HOME/julia/bin:$PATH"

  - julia --color=yes -e 'Pkg.add("PyCall")'

  - pip install --quiet tox
script:
  - make test-full
