language: python
os:
  - linux
python:
    - "2.7"
    - "3.6"
notifications:
  email: false
before_install:
  - ci/travis-before_install

  - export PATH="$HOME/julia/bin:$PATH"

  - julia --color=yes -e 'Pkg.add("PyCall")'

  - pip install --quiet tox-travis
script:
  - make test-full
