environment:

  TOXENV: py
  TOX_TESTENV_PASSENV: DISTUTILS_USE_SDK MSSdk INCLUDE LIB
  # https://packaging.python.org/guides/supporting-windows-using-appveyor/#testing-with-tox

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27-x64"
      JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    - PYTHON: "C:\\Python36-x64"
      JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"

matrix:
  allow_failures:
    - PYTHON: "C:\\Python27-x64"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"

# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $env:JULIA_URL,
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
  - set PATH=C:\projects\julia\bin;%PATH%

# Install Julia packages
  - julia --color=yes ci/prepare.jl

# Install Python packages
  - "%PYTHON%\\python.exe -m pip install --quiet tox"

build_script:
  # Empty so that it doesn't think it needs Visual Studio?
  - echo 'test'

test_script:
  - "%PYTHON%\\scripts\\tox"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
