#!/bin/bash -ex

# To be called from ../.travis.yml.  Based on diffeqpy/.travis.yml.

mkdir -p ~/Downloads

if [ "$TRAVIS_OS_NAME" == "linux" ]
then
    curl -L https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.2-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"
    tar xzf "$HOME/Downloads/julia.tar.gz" -C "$HOME/Downloads"
    cp -r "$(find "$HOME/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"
fi

if [ "$TRAVIS_OS_NAME" == "osx" ]
then
    curl -L https://julialang-s3.julialang.org/bin/mac/x64/0.6/julia-0.6.2-mac64.dmg -o "$HOME/Downloads/julia.dmg"
    hdiutil attach ~/Downloads/julia.dmg
    cp -r /Volumes/Julia*/Julia*/Contents/Resources/julia $HOME/julia
    hdiutil detach -force /Volumes/Julia*
fi

rm -rf ~/Downloads/julia*
